print("Naziah Williams")
print("My favorite musician is a Kpop artist, from the group called Monsta X. The member named Jooheon is my favorite. My favorite ablum of theirs is the most recent one, Fantasia X. My favorite song from the album is Flow.")
print("I would love to go on vacation to Greenland.")
print("A hobby of mines is drawing and I also like to listen to music.")
print("Todays date is July 14th,2020")